In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [2]:
df = pd.read_csv('data/faults.csv')

In [3]:
df.head()

X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  X_Perimeter  \
0         42         50     270900     270944           267           17   
1        645        651    2538079    2538108           108           10   
2        829        835    1553913    1553931            71            8   
3        853        860     369370     369415           176           13   
4       1289       1306     498078     498335          2409           60   

   Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
0           44              24220                     76   
1           30              11397                     84   
2           19               7972                     99   
3           45              18996                     99   
4          260             246930                     37   

   Maximum_of_Luminosity  Length_of_Conveyer  TypeOfSteel_A300  \
0                    108                1687                 1   
1                    123                1687                 1   
2                    125                1623                 1   
3                    126                1353                 0   
4                    126                1353                 0   

   TypeOfSteel_A400  Steel_Plate_Thickness  Edges_Index  Empty_Index  \
0                 0                     80       0.0498       0.2415   
1                 0                     80       0.7647       0.3793   
2                 0                    100       0.9710       0.3426   
3                 1                    290       0.7287       0.4413   
4                 1                    185       0.0695       0.4486   

   Square_Index  Outside_X_Index  Edges_X_Index  Edges_Y_Index  \
0        0.1818           0.0047         0.4706         1.0000   
1        0.2069           0.0036         0.6000         0.9667   
2        0.3333           0.0037         0.7500         0.9474   
3        0.1556           0.0052         0.5385         1.0000   
4        0.0662           0.0126         0.2833         0.9885   

   Outside_Global_Index  LogOfAreas  Log_X_Index  Log_Y_Index  \
0                   1.0      2.4265       0.9031       1.6435   
1                   1.0      2.0334       0.7782       1.4624   
2                   1.0      1.8513       0.7782       1.2553   
3                   1.0      2.2455       0.8451       1.6532   
4                   1.0      3.3818       1.2305       2.4099   

   Orientation_Index  Luminosity_Index  SigmoidOfAreas  Pastry  Z_Scratch  \
0             0.8182           -0.2913          0.5822       1          0   
1             0.7931           -0.1756          0.2984       1          0   
2             0.6667           -0.1228          0.2150       1          0   
3             0.8444           -0.1568          0.5212       1          0   
4             0.9338           -0.1992          1.0000       1          0   

   K_Scatch  Stains  Dirtiness  Bumps  Other_Faults  
0         0       0          0      0             0  
1         0       0          0      0             0  
2         0       0          0      0             0  
3         0       0          0      0             0  
4         0       0          0      0             0

In [4]:
df.columns

Index(['X_Minimum', 'X_Maximum', 'Y_Minimum', 'Y_Maximum', 'Pixels_Areas',
       'X_Perimeter', 'Y_Perimeter', 'Sum_of_Luminosity',
       'Minimum_of_Luminosity', 'Maximum_of_Luminosity', 'Length_of_Conveyer',
       'TypeOfSteel_A300', 'TypeOfSteel_A400', 'Steel_Plate_Thickness',
       'Edges_Index', 'Empty_Index', 'Square_Index', 'Outside_X_Index',
       'Edges_X_Index', 'Edges_Y_Index', 'Outside_Global_Index', 'LogOfAreas',
       'Log_X_Index', 'Log_Y_Index', 'Orientation_Index', 'Luminosity_Index',
       'SigmoidOfAreas', 'Pastry', 'Z_Scratch', 'K_Scatch', 'Stains',
       'Dirtiness', 'Bumps', 'Other_Faults'],
      dtype='object')

In [5]:
fault_cols = ['Pastry', 'Z_Scratch', 'K_Scatch', 'Stains', 'Dirtiness', 'Bumps', 'Other_Faults']

In [6]:
df['Fault_Types'] = df[fault_cols].idxmax(axis=1)

In [7]:
df.sample(5)

X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  X_Perimeter  \
1394       1090       1129    2312033    2312039           111           45   
1128        749        768     337093     337112           262           21   
860         615        622    2188217    2188232            57           13   
1491        244        261     184455     184498           460           49   
1437       1032       1046     404761     404774           111           24   

      Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
1394           19              12886                    109   
1128           19              29349                     88   
860            15               6560                    107   
1491           44              46972                     86   
1437           17              14697                    118   

      Maximum_of_Luminosity  Length_of_Conveyer  TypeOfSteel_A300  \
1394                    126                1358                 0   
1128                    133                1360                 0   
860                     127                1366                 0   
1491                    111                1692                 0   
1437                    143                1690                 1   

      TypeOfSteel_A400  Steel_Plate_Thickness  Edges_Index  Empty_Index  \
1394                 1                     40       0.3373       0.5256   
1128                 1                     40       0.8706       0.2742   
860                  1                    100       0.9004       0.4571   
1491                 1                    300       0.2884       0.3707   
1437                 0                    150       0.7621       0.3901   

      Square_Index  Outside_X_Index  Edges_X_Index  Edges_Y_Index  \
1394        0.1539           0.0287         0.8667         0.3158   
1128        1.0000           0.0140         0.9048         1.0000   
860         0.4667           0.0051         0.5385         1.0000   
1491        0.3954           0.0100         0.3469         0.9773   
1437        0.9286           0.0083         0.5833         0.7647   

      Outside_Global_Index  LogOfAreas  Log_X_Index  Log_Y_Index  \
1394                   0.0      2.0453       1.5911       0.7782   
1128                   0.5      2.4183       1.2787       1.2787   
860                    1.0      1.7559       0.8451       1.1761   
1491                   1.0      2.6628       1.2305       1.6335   
1437                   0.0      2.0453       1.1461       1.1139   

      Orientation_Index  Luminosity_Index  SigmoidOfAreas  Pastry  Z_Scratch  \
1394            -0.8461           -0.0931          0.3882       0          0   
1128             0.0000           -0.1248          0.5967       0          0   
860              0.5333           -0.1009          0.2116       0          0   
1491             0.6047           -0.2022          0.9457       0          0   
1437            -0.0714            0.0344          0.3097       0          0   

      K_Scatch  Stains  Dirtiness  Bumps  Other_Faults   Fault_Types  
1394         0       0          0      0             1  Other_Faults  
1128         0       0          0      1             0         Bumps  
860          0       0          1      0             0     Dirtiness  
1491         0       0          0      0             1  Other_Faults  
1437         0       0          0      0             1  Other_Faults

In [8]:
df.drop(columns = fault_cols, inplace=True)

In [9]:
df.sample(5)

X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  X_Perimeter  \
851         621        633    2076516    2076679           969          124   
1558       1392       1415    1215744    1215749            82           23   
798        1094       1101    1506525    1506531            17            7   
839         625        631    1934306    1934337           127           19   
717          83        202    7655518    7655567          3455          157   

      Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
851           163             103558                     92   
1558            6              10827                    123   
798             7               2310                    129   
839            31              13897                     99   
717            86             373412                     67   

      Maximum_of_Luminosity  Length_of_Conveyer  TypeOfSteel_A300  \
851                     141                1364                 0   
1558                    141                1630                 1   
798                     149                1360                 0   
839                     125                1364                 0   
717                     127                1360                 0   

      TypeOfSteel_A400  Steel_Plate_Thickness  Edges_Index  Empty_Index  \
851                  1                    100       0.9106       0.5046   
1558                 0                    100       0.2638       0.2870   
798                  1                     50       0.3809       0.5952   
839                  1                    100       0.9164       0.3172   
717                  1                     40       0.1221       0.4075   

      Square_Index  Outside_X_Index  Edges_X_Index  Edges_Y_Index  \
851         0.0736           0.0088         0.0968         1.0000   
1558        0.2174           0.0141         1.0000         0.8333   
798         0.8571           0.0052         1.0000         0.8571   
839         0.1936           0.0044         0.3158         1.0000   
717         0.4118           0.0875         0.7580         0.5698   

      Outside_Global_Index  LogOfAreas  Log_X_Index  Log_Y_Index  \
851                    1.0      2.9863       1.0792       2.2122   
1558                   0.0      1.9138       1.3617       0.6990   
798                    0.0      1.2305       0.8451       0.7782   
839                    1.0      2.1038       0.7782       1.4914   
717                    0.0      3.5385       2.0756       1.6902   

      Orientation_Index  Luminosity_Index  SigmoidOfAreas   Fault_Types  
851              0.9264           -0.1651          1.0000     Dirtiness  
1558            -0.7826            0.0315          0.2230  Other_Faults  
798             -0.1429            0.0616          0.1499        Stains  
839              0.8065           -0.1451          0.3154     Dirtiness  
717             -0.5882           -0.1556          1.0000      K_Scatch

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1941 entries, 0 to 1940
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   X_Minimum              1941 non-null   int64  
 1   X_Maximum              1941 non-null   int64  
 2   Y_Minimum              1941 non-null   int64  
 3   Y_Maximum              1941 non-null   int64  
 4   Pixels_Areas           1941 non-null   int64  
 5   X_Perimeter            1941 non-null   int64  
 6   Y_Perimeter            1941 non-null   int64  
 7   Sum_of_Luminosity      1941 non-null   int64  
 8   Minimum_of_Luminosity  1941 non-null   int64  
 9   Maximum_of_Luminosity  1941 non-null   int64  
 10  Length_of_Conveyer     1941 non-null   int64  
 11  TypeOfSteel_A300       1941 non-null   int64  
 12  TypeOfSteel_A400       1941 non-null   int64  
 13  Steel_Plate_Thickness  1941 non-null   int64  
 14  Edges_Index            1941 non-null   float64
 15  Empt

In [11]:
df['Fault_Types'].value_counts()

Fault_Types
Other_Faults    673
Bumps           402
K_Scatch        391
Z_Scratch       190
Pastry          158
Stains           72
Dirtiness        55
Name: count, dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Fault_Types'] = le.fit_transform(df['Fault_Types'])

In [13]:
df.describe()

X_Minimum    X_Maximum     Y_Minimum     Y_Maximum   Pixels_Areas  \
count  1941.000000  1941.000000  1.941000e+03  1.941000e+03    1941.000000   
mean    571.136012   617.964451  1.650685e+06  1.650739e+06    1893.878413   
std     520.690671   497.627410  1.774578e+06  1.774590e+06    5168.459560   
min       0.000000     4.000000  6.712000e+03  6.724000e+03       2.000000   
25%      51.000000   192.000000  4.712530e+05  4.712810e+05      84.000000   
50%     435.000000   467.000000  1.204128e+06  1.204136e+06     174.000000   
75%    1053.000000  1072.000000  2.183073e+06  2.183084e+06     822.000000   
max    1705.000000  1713.000000  1.298766e+07  1.298769e+07  152655.000000   

        X_Perimeter   Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
count   1941.000000   1941.000000       1.941000e+03            1941.000000   
mean     111.855229     82.965997       2.063121e+05              84.548686   
std      301.209187    426.482879       5.122936e+05              32.134276   
min        2.000000      1.000000       2.500000e+02               0.000000   
25%       15.000000     13.000000       9.522000e+03              63.000000   
50%       26.000000     25.000000       1.920200e+04              90.000000   
75%       84.000000     83.000000       8.301100e+04             106.000000   
max    10449.000000  18152.000000       1.159141e+07             203.000000   

       Maximum_of_Luminosity  Length_of_Conveyer  TypeOfSteel_A300  \
count            1941.000000         1941.000000       1941.000000   
mean              130.193715         1459.160227          0.400309   
std                18.690992          144.577823          0.490087   
min                37.000000         1227.000000          0.000000   
25%               124.000000         1358.000000          0.000000   
50%               127.000000         1364.000000          0.000000   
75%               140.000000         1650.000000          1.000000   
max               253.000000         1794.000000          1.000000   

       TypeOfSteel_A400  Steel_Plate_Thickness  Edges_Index  Empty_Index  \
count       1941.000000            1941.000000  1941.000000  1941.000000   
mean           0.599691              78.737764     0.331715     0.414203   
std            0.490087              55.086032     0.299712     0.137261   
min            0.000000              40.000000     0.000000     0.000000   
25%            0.000000              40.000000     0.060400     0.315800   
50%            1.000000              70.000000     0.227300     0.412100   
75%            1.000000              80.000000     0.573800     0.501600   
max            1.000000             300.000000     0.995200     0.943900   

       Square_Index  Outside_X_Index  Edges_X_Index  Edges_Y_Index  \
count   1941.000000      1941.000000    1941.000000    1941.000000   
mean       0.570767         0.033361       0.610529       0.813472   
std        0.271058         0.058961       0.243277       0.234274   
min        0.008300         0.001500       0.014400       0.048400   
25%        0.361300         0.006600       0.411800       0.596800   
50%        0.555600         0.010100       0.636400       0.947400   
75%        0.818200         0.023500       0.800000       1.000000   
max        1.000000         0.875900       1.000000       1.000000   

       Outside_Global_Index   LogOfAreas  Log_X_Index  Log_Y_Index  \
count           1941.000000  1941.000000  1941.000000  1941.000000   
mean               0.575734     2.492388     1.335686     1.403271   
std                0.482352     0.788930     0.481612     0.454345   
min                0.000000     0.301000     0.301000     0.000000   
25%                0.000000     1.924300     1.000000     1.079200   
50%                1.000000     2.240600     1.176100     1.322200   
75%                1.000000     2.914900     1.518500     1.732400   
max                1.000000     5.183700     3.074100     4.258700   

       Orientati

In [14]:
X = df.drop(columns=['Fault_Types'])
y = df['Fault_Types']

In [15]:
binary_cols = ['TypeOfSteel_A300', 'TypeOfSteel_A400']
num_cols = X.columns.difference(binary_cols)

In [16]:
from sklearn.preprocessing import RobustScaler
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ('num', RobustScaler(), num_cols)
    ],
    remainder='passthrough'   # keeps binary columns as-is
)

X_scaled = preprocessor.fit_transform(X)


In [17]:
X_scaled = pd.DataFrame(
    X_scaled,
    columns=list(num_cols) + list(binary_cols)
)

In [18]:
X_scaled.head()
y.sample(10)

774     5
1304    3
1011    0
274     6
891     0
1014    0
1874    3
1760    3
902     0
1820    3
Name: Fault_Types, dtype: int32

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)


In [20]:
from sklearn.ensemble import RandomForestClassifier

rf1 = RandomForestClassifier()

rf1.fit(X_train, y_train)

RandomForestClassifier()

In [21]:
from sklearn.metrics import accuracy_score, classification_report 

y_pred = rf1.predict(X_test)

print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.7737789203084833
              precision    recall  f1-score   support

           0       0.63      0.64      0.63        72
           1       0.60      0.75      0.67         8
           2       0.96      0.93      0.94        83
           3       0.71      0.78      0.74       143
           4       0.65      0.45      0.53        29
           5       1.00      0.92      0.96        13
           6       0.95      0.88      0.91        41

    accuracy                           0.77       389
   macro avg       0.79      0.76      0.77       389
weighted avg       0.78      0.77      0.77       389



In [22]:
from sklearn.model_selection import GridSearchCV

In [23]:
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt', 'log2']
}


In [24]:
grid = GridSearchCV(
    estimator=rf1,
    param_grid=param_grid,
    cv=5,
    scoring='f1_macro',
    n_jobs=-1,
    verbose=2
)

grid.fit(X_train, y_train)


Fitting 5 folds for each of 48 candidates, totalling 240 fits


GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [None, 10, 20],
                         'max_features': ['sqrt', 'log2'],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [100, 200]},
             scoring='f1_macro', verbose=2)

In [25]:
print("Best Parameters:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

Best Parameters: {'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
Best CV Score: 0.8084336061428529


In [26]:
best_model = grid.best_estimator_

In [27]:
from sklearn.metrics import classification_report, confusion_matrix

y_test_pred = best_model.predict(X_test)

print(classification_report(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))


              precision    recall  f1-score   support

           0       0.65      0.61      0.63        72
           1       0.60      0.75      0.67         8
           2       0.96      0.93      0.94        83
           3       0.71      0.78      0.75       143
           4       0.62      0.52      0.57        29
           5       1.00      0.92      0.96        13
           6       0.95      0.88      0.91        41

    accuracy                           0.78       389
   macro avg       0.79      0.77      0.77       389
weighted avg       0.78      0.78      0.78       389

[[ 44   2   0  22   4   0   0]
 [  0   6   0   2   0   0   0]
 [  0   0  77   6   0   0   0]
 [ 20   2   2 112   5   0   2]
 [  3   0   0  11  15   0   0]
 [  1   0   0   0   0  12   0]
 [  0   0   1   4   0   0  36]]


In [28]:
# baseline model
rf_baseline = RandomForestClassifier(class_weight='balanced', random_state=42)
rf_baseline.fit(X_train, y_train)

y_base_pred = rf_baseline.predict(X_test)

print("Baseline:")
print(classification_report(y_test, y_base_pred))

print("\nTuned:")
print(classification_report(y_test, y_test_pred))


Baseline:
              precision    recall  f1-score   support

           0       0.61      0.60      0.60        72
           1       0.67      0.75      0.71         8
           2       0.96      0.93      0.94        83
           3       0.70      0.76      0.73       143
           4       0.61      0.48      0.54        29
           5       1.00      0.92      0.96        13
           6       0.95      0.88      0.91        41

    accuracy                           0.76       389
   macro avg       0.78      0.76      0.77       389
weighted avg       0.77      0.76      0.76       389


Tuned:
              precision    recall  f1-score   support

           0       0.65      0.61      0.63        72
           1       0.60      0.75      0.67         8
           2       0.96      0.93      0.94        83
           3       0.71      0.78      0.75       143
           4       0.62      0.52      0.57        29
           5       1.00      0.92      0.96        13
      